language: scala
scala:
  - 2.11.0-RC4
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:rethinkdb/ppa
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq rethinkdb
  - sudo apt-get install -qq protobuf-compiler
  - sudo ldconfig
before_script:
  - rethinkdb --daemon
  - rethinkdb admin set auth foobar
branches:
  only:
    - master
