language: scala
scala:
  - 2.10.1
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:rethinkdb/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq rethinkdb
before_script:
  - rethinkdb --daemon
branches:
  only:
    - master
